### ISSUE TITLE
RateLimitExceededEvent.java file is missing in  1.7.5.RELEASE

### ISSUE THREAD

**Issue by sharunthomas** [marcosbarbero/spring-cloud-zuul-ratelimit#345]
**Describe the question**
RateLimitExceededEvent.java file is missing in  1.7.5.RELEASE

**Additional context**
![image](https://user-images.githubusercontent.com/17807916/82535877-2ef48380-9b65-11ea-9baf-58ab4f583341.png)

**Comment by sharunthomas** [comment]
![image](https://user-images.githubusercontent.com/17807916/82535948-4e8bac00-9b65-11ea-8013-cf1ce8931b82.png)

**Comment by marcosbarbero** [comment]
Hi @sharunthomas 
This class is not there because it's a new feature, and as you can see [here the line `1.7.x` has hit its End-Of-Life (EOL) and is no longer maintained](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/tree/1.7.x#spring-cloud-zuul-rate-limit-eol).

I suggest you upgrade to Spring Boot 2 and use the latest version of this library.
