### ISSUE TITLE
both use quota and limit parameters,redis will execute incrby command twice

### ISSUE THREAD

**Issue by fengshuzi** [marcosbarbero/spring-cloud-zuul-ratelimit#438]
both use quota and limit parameters,redis will execute incrby command twice

![image](https://user-images.githubusercontent.com/5603582/115364905-73b1f000-a1f6-11eb-9827-9d302ee5fb33.png)

**Comment by marcosbarbero** [comment]
Hi @fengshuzi, please follow this template to report bugs

---
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment & Versioning (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Spring Boot Version
 - Spring Cloud Version
 - Spring Cloud Rate Limit Version

**Additional context**
Add any other context about the problem here.
